/**
 * Mealist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateMenuRequest { 
    name?: string;
    language?: CreateMenuRequest.LanguageEnum;
    file: Blob;
}
export namespace CreateMenuRequest {
    export type LanguageEnum = 'eng' | 'rus' | 'ukr' | 'bel' | 'pol' | 'deu';
    export const LanguageEnum = {
        Eng: 'eng' as LanguageEnum,
        Rus: 'rus' as LanguageEnum,
        Ukr: 'ukr' as LanguageEnum,
        Bel: 'bel' as LanguageEnum,
        Pol: 'pol' as LanguageEnum,
        Deu: 'deu' as LanguageEnum
    };
}


