/**
 * Mealist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Restaurant } from './restaurant';
import { QrMenuItem } from './qrMenuItem';

export interface QrMenu {
  id?: string;
  name?: string;
  displayName?: string;
  restaurant?: Restaurant;
  sectionsToShow?: Array<string>;
  primaryColor?: string;
  secondaryColor?: string;
  backgroundColor: string;
  fontColor?: string;
  scanCount?: number;
  stopList?: Array<string>;
  loadingPlaceholderIndex?: number;
  loadingPlaceholderUrl?: string;
  urlSuffix?: string;
  items?: Array<QrMenuItem>;
  creationDate?: string;
  modificationDate?: string;
}
