/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CreateRestaurantRequest: {
      name: string;
      address: string;
      city?: string;
      description?: string;
      wifiName?: string;
      wifiPassword?: string;
      instagramUrl?: string;
      vkUrl?: string;
      facebookUrl?: string;
      tripAdvisorUrl?: string;
    };
    Restaurant: {
      id?: string;
      name: string;
      address: string;
      city?: string;
      description?: string;
      mapsView?: string;
      wifiName?: string;
      wifiPassword?: string;
      instagramUrl?: string;
      vkUrl?: string;
      facebookUrl?: string;
      tripAdvisorUrl?: string;
    };
    Menu: {
      id?: number;
      name: string;
      description?: string;
    };
    Code: {
      menuId: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
