export enum MenuProcessingStatus {
  NOT_PARSED = 'NOT_PARSED',
  PARSING_IN_PROGRESS = 'PARSING_IN_PROGRESS',
  PARSING_FAILED = 'PARSING_FAILED',
  PARSING_COMPLETED = 'PARSING_COMPLETED',
  OCR_IN_PROGRESS = 'OCR_IN_PROGRESS',
  OCR_FAILED = 'OCR_FAILED',
  OCR_COMPLETED = 'OCR_COMPLETED',
  REVIEWED = 'REVIEWED',
}
