openapi: 3.0.0
info:
  title: Mealist API
  version: 1.0.0
paths: {}
components:
  schemas:
    Restaurant:
      type: "object"
      properties:
        id:
          type: string
        name:
          type: string
        address:
          type: string
        city:
          type: string
        description:
          type: string
        wifiName:
          type: string
        wifiPassword:
          type: string
        instagramUrl:
          type: string
        vkUrl:
          type: string
        facebookUrl:
          type: string
        tripAdvisorUrl:
          type: string
      required:
        - name
        - address
        - city
    CreateMenuRequest:
      type: "object"
      properties:
        name:
          type: string
        file:
          type: string
          format: binary
      required:
        - file
    Menu:
      type: "object"
      properties:
        id:
          type: string
        name:
          type: string
        images:
          type: array
          items:
            type: string
        status:
          type: string
        menuCompressed:
          type: boolean
        dishesCount:
          type: integer
        pagesCount:
          type: integer
        parsingProgress:
          type: integer
        previewImageUrl:
          type: string
        originalFileUrl:
          type: string
        stopListEnabled:
          type: boolean
        stopColor:
          type: string
        stopStyle:
          type: string
        creationDate:
          type: string
          format: date-time
        markups:
          type: array
          items:
            type: array
            items:
              $ref: "#/components/schemas/MenuLine"
      required:
        - name
    MenuLine:
      type: "object"
      properties:
        text:
          type: string
        tag:
          type: string
        box:
          type: array
          items:
            type: array
            items:
              type: number
        x1:
          type: number
        y1:
          type: number
        x2:
          type: number
        y2:
          type: number
        editSelected:
          type: boolean
        viewSelected:
          type: boolean
        hover:
          type: boolean
        children:
          type: array
          items:
            $ref: "#/components/schemas/MenuLine"
      required:
        - x1
        - x2
        - y1
        - y2
    Code:
      type: "object"
      properties:
        menuId:
          type: integer
      required:
        - menuId
