openapi: 3.0.0
info:
  title: Mealist API
  version: 1.0.0
paths: {}
components:
  schemas:
    Restaurant:
      type: "object"
      properties:
        id:
          type: string
        name:
          type: string
        address:
          type: string
        city:
          type: string
        description:
          type: string
        wifiName:
          type: string
        wifiPassword:
          type: string
        instagramUrl:
          type: string
        vkUrl:
          type: string
        facebookUrl:
          type: string
        tripAdvisorUrl:
          type: string
      required:
        - name
        - address
        - city
    CreateMenuRequest:
      type: "object"
      properties:
        name:
          type: string
        language:
          type: string
          enum:
            - "eng"
            - "rus"
            - "ukr"
            - "bel"
            - "pol"
            - "deu"
        file:
          type: string
          format: binary
      required:
        - file
    Menu:
      type: "object"
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
          enum:
            - "NOT_PARSED"
            - "PARSING_IN_PROGRESS"
            - "PARSING_FAILED"
            - "PARSING_COMPLETED"
            - "OCR_IN_PROGRESS"
            - "OCR_FAILED"
            - "OCR_COMPLETED"
            - "REVIEWED"
        dishesCount:
          type: integer
        originalFileUrl:
          type: string
        stopColor:
          type: string
        stopStyle:
          type: string
        creationDate:
          type: string
          format: date-time
        modificationDate:
          type: string
          format: date-time
        pages:
          type: array
          items:
            $ref: "#/components/schemas/MenuPage"
      required:
        - name
    MenuPage:
      type: "object"
      properties:
        pageNumber:
          type: integer
        imageUrl:
          type: string
        markup:
          type: array
          items:
            $ref: "#/components/schemas/MenuLine"
      required:
        - pageNumber
        - imageUrl
    MenuLine:
      type: "object"
      properties:
        text:
          type: string
        x1:
          type: number
        y1:
          type: number
        x2:
          type: number
        y2:
          type: number
      required:
        - x1
        - x2
        - y1
        - y2
    Code:
      type: "object"
      properties:
        menuId:
          type: integer
      required:
        - menuId
    ReadOnlyQrMenu:
      type: "object"
      properties:
        title:
          type: string
        restaurant:
          $ref: "#/components/schemas/Restaurant"
        sectionsToShow:
          type: array
          items:
            type: string
        style:
          $ref: "#/components/schemas/QrMenuStyle"
        loadingPlaceholderUrl:
          type: string
        menus:
          type: array
          items:
            $ref: "#/components/schemas/ReadonlyQrMenuItem"
      required:
        - restaurant
        - sectionsToShow
        - style
        - loadingPlaceholderUrl
        - menus
    QrMenu:
      type: "object"
      properties:
        id:
          type: string
        name:
          type: string
        urlSuffix:
          type: string
        title:
          type: string
        restaurant:
          $ref: "#/components/schemas/Restaurant"
        sectionsToShow:
          type: array
          items:
            type: string
        style:
          $ref: "#/components/schemas/QrMenuStyle"
        scanCount:
          type: integer
        loadingPlaceholderMenuIndex:
          type: integer
        loadingPlaceholderUrl:
          type: string
        menus:
          type: array
          items:
            $ref: "#/components/schemas/QrMenuItem"
        creationDate:
          type: string
          format: date-time
        modificationDate:
          type: string
          format: date-time
      required:
        - id
        - name
        - restaurant
        - urlSuffix
        - sectionsToShow
        - style
        - loadingPlaceholderUrl
        - menus
        - creationDate
    QrMenuItem:
      type: "object"
      properties:
        stopColor:
          type: string
        stopStyle:
          type: string
        title:
          type: string
        menu:
          $ref: "#/components/schemas/Menu"
    ReadonlyQrMenuItem:
      type: "object"
      properties:
        stopColor:
          type: string
        stopStyle:
          type: string
        title:
          type: string
        pages:
          type: array
          items:
            $ref: "#/components/schemas/MenuPage"
    QrMenuStyle:
      type: "object"
      properties:
        headerColor:
          type: string
        actionsColor:
          type: string
        fontColor:
          type: string
        backgroundColor:
          type: string
    CreateQrMenuRequest:
      type: "object"
      properties:
        name:
          type: string
        urlSuffix:
          type: string
        title:
          type: string
        restaurantId:
          type: string
        sectionsToShow:
          type: array
          items:
            type: string
        style:
          $ref: "#/components/schemas/QrMenuStyle"
        loadingPlaceholder:
          $ref: "#/components/schemas/CreateLoadingPlaceholderRequest"
        menus:
          type: array
          items:
            $ref: "#/components/schemas/CreateQrMenuItem"
        file:
          type: string
          format: binary
      required:
        - restaurantId
        - name
        - urlSuffix
        - sectionsToShow
        - style
        - loadingPlaceholder
        - menus
    CreateLoadingPlaceholderRequest:
      type: "object"
      properties:
        menuIndex:
          type: integer
    CreateQrMenuItem:
      type: "object"
      properties:
        title:
          type: string
        menuId:
          type: string
      required:
        - title
        - menuId
