/**
 * Mealist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QrMenuStyle } from './qrMenuStyle';
import { ReadonlyRestaurant } from './readonlyRestaurant';
import { ReadonlyQrMenuItem } from './readonlyQrMenuItem';


export interface ReadonlyQrMenu { 
    title?: string;
    restaurant: ReadonlyRestaurant;
    sectionsToShow: Array<string>;
    style: QrMenuStyle;
    loadingPlaceholderUrl: string;
    menus: Array<ReadonlyQrMenuItem>;
}

