/**
 * Mealist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateLoadingPlaceholderRequest } from './createLoadingPlaceholderRequest';
import { QrMenuStyle } from './qrMenuStyle';
import { CreateQrMenuItem } from './createQrMenuItem';


export interface UpdateQrMenuRequest { 
    name: string;
    urlSuffix: string;
    title?: string;
    restaurantId: string;
    sectionsToShow: Array<string>;
    style: QrMenuStyle;
    loadingPlaceholder: CreateLoadingPlaceholderRequest;
    menus: Array<CreateQrMenuItem>;
}

