/**
 * Mealist API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MenuLine { 
    text?: string;
    tag?: string;
    box?: Array<Array<number>>;
    x1: number;
    y1: number;
    x2: number;
    y2: number;
    editSelected?: boolean;
    viewSelected?: boolean;
    hover?: boolean;
    children?: Array<MenuLine>;
}

