openapi: 3.0.0
info:
  title: Mealist API
  version: 1.0.0
paths: {}
components:
  schemas:
    Restaurant:
      type: "object"
      properties:
        id:
          type: string
        name:
          type: string
        address:
          type: string
        city:
          type: string
        description:
          type: string
        wifiName:
          type: string
        wifiPassword:
          type: string
        instagramUrl:
          type: string
        vkUrl:
          type: string
        facebookUrl:
          type: string
        tripAdvisorUrl:
          type: string
      required:
        - name
        - address
        - city
    CreateMenuRequest:
      type: "object"
      properties:
        name:
          type: string
        language:
          type: string
          enum:
            - "eng"
            - "rus"
            - "ukr"
            - "bel"
            - "pol"
            - "deu"
        file:
          type: string
          format: binary
      required:
        - file
    Menu:
      type: "object"
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
          enum:
            - "NOT_PARSED"
            - "PARSING_IN_PROGRESS"
            - "PARSING_FAILED"
            - "PARSING_COMPLETED"
            - "OCR_IN_PROGRESS"
            - "OCR_FAILED"
            - "OCR_COMPLETED"
            - "REVIEWED"
        dishesCount:
          type: integer
        originalFileUrl:
          type: string
        stopColor:
          type: string
        stopStyle:
          type: string
        creationDate:
          type: string
          format: date-time
        modificationDate:
          type: string
          format: date-time
        pages:
          type: array
          items:
            $ref: "#/components/schemas/MenuPage"
      required:
        - name
    MenuPage:
      type: "object"
      properties:
        pageNumber:
          type: integer
        imageUrl:
          type: string
        markup:
          type: array
          items:
            $ref: "#/components/schemas/MenuLine"
      required:
        - pageNumber
        - imageUrl
    MenuLine:
      type: "object"
      properties:
        text:
          type: string
        x1:
          type: number
        y1:
          type: number
        x2:
          type: number
        y2:
          type: number
      required:
        - x1
        - x2
        - y1
        - y2
    Code:
      type: "object"
      properties:
        menuId:
          type: integer
      required:
        - menuId
    QrMenu:
      type: "object"
      properties:
        id:
          type: string
        name:
          type: string
        displayName:
          type: string
        restaurant:
          $ref: "#/components/schemas/Restaurant"
        primaryColor:
          type: string
        secondaryColor:
          type: string
        fontColor:
          type: string
        scanCount:
          type: integer
        stopList:
          type: array
          items:
            type: string
        hideSections:
          type: array
          items:
            type: string
        previewIndex:
          type: integer
        urlSuffix:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/QrMenuItem"
        creationDate:
          type: string
          format: date-time
        modificationDate:
          type: string
          format: date-time
      required:
        - menuId
        - restaurantId
    QrMenuItem:
      type: "object"
      properties:
        menu:
          $ref: "#/components/schemas/Menu"
        title:
          type: string
        thumbnailIndex:
          type: integer
    CreateQrMenuRequest:
      type: "object"
      properties:
        name:
          type: string
        displayName:
          type: string
        primaryColor:
          type: string
        secondaryColor:
          type: string
        fontColor:
          type: string
        previewIndex:
          type: integer
        urlSuffix:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/CreateQrMenuItem"
        restaurantId:
          type: string
      required:
        - menuId
        - restaurantId
    CreateQrMenuItem:
      type: "object"
      properties:
        title:
          type: string
        thumbnailIndex:
          type: integer
        menuId:
          type: string
      required:
        - title
        - thumbnailIndex
        - menuId
